services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend-dev
