services:
  app:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    container_name: bloglist-frontend

  server:
    image: bloglist-backend
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    env_file:
      - ./bloglist-backend/.env
    container_name: bloglist-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
